### ISSUE TITLE
uncertain BeautifulSoup / bs4 usage

### ISSUE THREAD

**Issue by richard-jones** [ourresearch/total-impact-core#67] opened 2012-04-10 09:28 UTC
The setup.py now includes beautiful soups 3 and 4 as the dependency set.  Why is this?  We should be using one version or another, or things are going to get very confusing, particularly as BeautifulStoneSoup no longer exists in bs4.  Either we should stick to version 3, or we should properly port to version 4, but we shouldn't be in the half-way house that we're currently in.

**Comment by hpiwowar** [comment] 2012-04-11 02:08
duplicate of #38

**Closed as completed by hpiwowar** 2012-04-11 02:08 UTC
