### ISSUE TITLE
article with no DOI getting different metrics than inputting the article URL

### ISSUE THREAD

**Issue by jalperin** [ourresearch/total-impact-core#131] opened 2013-07-11 03:37 UTC
I imported articles from my [Google Scholar profile](http://scholar.google.com/citations?user=QW-eo0MAAAAJ&hl=en) which has the [this article](http://scholar.google.com/citations?view_op=view_citation&hl=en&user=QW-eo0MAAAAJ&citation_for_view=QW-eo0MAAAAJ:W7OEmFMy1HYC) (Scholarly Communication Strategies in Latin America's Research-Intensive Universities)

In the "Articles section" of my profile, it appears to have no metrics. 

Yet, if I input the [article URL](http://ess.iesalc.unesco.org.ve/index.php/ess/article/view/409/347) it has several metrics. 

I also get different metrics if I do the abstract URL: http://ess.iesalc.unesco.org.ve/index.php/ess/article/view/409 and the PDF url: http://ess.iesalc.unesco.org.ve/index.php/ess/article/view/409/347

Finally, the delicious bookmark link does not go to the right place

See everything on my [ImpactStory profile](http://impactstory.org/JuanPabloAlperin)

**Comment by jalperin** [comment] 2013-07-11 03:44
note that the article in the GS profile has two different URL's (one is a self-archived copy).

**Comment by hpiwowar** [comment] 2013-08-17 02:59
requested bibtex file from juan to understand current state of these issues with a fresh google scholar import, after recent google scholar import fixes.

**Comment by jalperin** [comment] 2013-08-17 04:42
Here's my bibtex as of today. Let me know if you need more clarification/explanation. http://cl.ly/QtC7

**Comment by hpiwowar** [comment] 2013-08-17 05:39
Thanks Juan!

It seems the issue is Google Scholar's bibtex export doesn't include the URLs to the articles, only their titles and bibliographic information.  

We can figure out the URL if the paper has a DOI by looking it up in crossref, and sometimes we can figure the URL out by looking up the title in Mendeley.  I did check and can see your paper in Mendeley, but the Mendeley api search and indeed the normal Mendeley site search doesn't seem to find it by title.  So we don't have a URL, so we can't find any metrics.

The issue is the similar for merging the metrics for the abstract and PDF pages for your other article: we don't have any automated way to know these are the same articles.

The Delicious link, though, that is fixed :)  
And if you reimport your google scholar bibtex all the characters should render properly (you can delete duplicates by clicking the X that appears in the left when you hover on the title of a paper).

We'll keep thinking about how to do a better job of the URL problems above, but we don't have any possibilities on the horizon I'm afraid.  I'm going to close this ticket for now.  Thanks again for writing to tell us about the problems!

**Closed as completed by hpiwowar** 2013-08-17 05:39 UTC
